### ISSUE TITLE
Problem creating AMI, fails at SetLogRetentionFunctionRetention

### ISSUE THREAD

**Issue by Tarang** [spotty-cloud/spotty#76]
It's quite hard to debug this one. 

```
spotty aws create-ami                                                                                                                                                                                         (py37)
Waiting for the AMI to be created...
  - creating IAM role for the instance...
Error:
------
Stack "spotty-ami-spottyami" was not created.
Please, see CloudFormation logs for the details.
```

Cloudformation logs
<img width="908" alt="image" src="https://user-images.githubusercontent.com/1616628/95667837-4b966400-0bb7-11eb-9901-21faaafbbfb0.png">

The Cloudwatch logs (an extract of the issue):
```
INFO	FAILED:
 ResourceNotFoundException: The specified log group does not exist.
    at Request.extractError (/var/runtime/node_modules/aws-sdk/lib/protocol/json.js:51:27)
    at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/request.js:688:14)
    at Request.transition (/var/runtime/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/var/runtime/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /var/runtime/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:690:12)
    at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:116:18) {
  code: 'ResourceNotFoundException'
```

Spotty Version: 1.2.4

**Comment by apls777** [comment]
The functionality of creating an AMI won't be supported anymore. Is there a reason you're not using the default Amazon Deep Learning AMI?

**Comment by Tarang** [comment]
I didn't know that. So you don't need to do create-ami anymore?

**Comment by apls777** [comment]
No, you don't. Spotty is using Amazon Deep Learning AMI by default.

**Comment by Tarang** [comment]
I missed the update note! Thanks
